/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class elfp_capstonewrapper_CapstoneWrapper */

#ifndef _Included_elfp_capstonewrapper_CapstoneWrapper
#define _Included_elfp_capstonewrapper_CapstoneWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     elfp_capstonewrapper_CapstoneWrapper
 * Method:    disas
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_elfp_capstonewrapper_CapstoneWrapper_disas
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
